// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {connection} from '../models';
import {jvm} from '../models';

export function AddManagedService(arg1:app.AddServiceRequest):Promise<connection.QueryResult>;

export function ApplyDataRootDirectory(arg1:string,arg2:boolean):Promise<connection.QueryResult>;

export function ApplyLogDirectory(arg1:string):Promise<connection.QueryResult>;

export function ApplyServyEnginePath(arg1:string):Promise<connection.QueryResult>;

export function CancelApplicationQuit():Promise<connection.QueryResult>;

export function CheckForUpdates():Promise<connection.QueryResult>;

export function CheckForUpdatesSilently():Promise<connection.QueryResult>;

export function CheckServicePorts(arg1:Array<number>):Promise<connection.QueryResult>;

export function ConfigureGlobalProxy(arg1:boolean,arg2:connection.ProxyConfig):Promise<connection.QueryResult>;

export function ControlWindowsService(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConnections(arg1:Array<string>):Promise<void>;

export function DescribeJavaRuntime(arg1:string):Promise<connection.QueryResult>;

export function DetectJavaRuntimes():Promise<connection.QueryResult>;

export function DismissSecurityUpdateReminder():Promise<app.SecurityUpdateStatus>;

export function DownloadUpdate():Promise<connection.QueryResult>;

export function DuplicateConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function ForceQuitApplication():Promise<connection.QueryResult>;

export function GetAppInfo():Promise<connection.QueryResult>;

export function GetBrandIconDataURL(arg1:string):Promise<string>;

export function GetDataRootDirectoryInfo():Promise<connection.QueryResult>;

export function GetDownloadSourceConfig():Promise<app.DownloadSourceConfig>;

export function GetEditableSavedConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function GetGlobalProxyConfig():Promise<connection.QueryResult>;

export function GetMainWindowDisplayLayout():Promise<connection.QueryResult>;

export function GetSavedConnections():Promise<Array<connection.SavedConnectionView>>;

export function GetSecurityUpdateStatus():Promise<app.SecurityUpdateStatus>;

export function GetServiceDirUsage(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetServiceLogRetentionDays():Promise<connection.QueryResult>;

export function GetServyEngineConfig():Promise<connection.QueryResult>;

export function GetUpdateChannel():Promise<connection.QueryResult>;

export function GetUpdateDownloadTask():Promise<connection.QueryResult>;

export function GetWindowsServiceDetail(arg1:string):Promise<connection.QueryResult>;

export function ImportLegacyConnections(arg1:Array<connection.SavedConnectionInput>):Promise<Array<connection.SavedConnectionView>>;

export function ImportLegacyGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function InstallUpdateAndRestart(arg1:boolean):Promise<connection.QueryResult>;

export function JVMApplyChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMCancelDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function JVMExecuteDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:jvm.DiagnosticCommandRequest):Promise<connection.QueryResult>;

export function JVMGetMonitoringHistory(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMGetValue(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMListAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListDiagnosticAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListResources(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMPreviewChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMProbeCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMProbeDiagnosticCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStartDiagnosticSession(arg1:connection.ConnectionConfig,arg2:jvm.DiagnosticSessionRequest):Promise<connection.QueryResult>;

export function JVMStartMonitoring(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStopMonitoring(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function ListInstalledFontFamilies():Promise<connection.QueryResult>;

export function ListServiceEngineEvents(arg1:string):Promise<connection.QueryResult>;

export function ListServiceLogFiles(arg1:string):Promise<connection.QueryResult>;

export function ListWindowsServices():Promise<connection.QueryResult>;

export function LocateServyEngine():Promise<connection.QueryResult>;

export function LogWindowDiagnostic(arg1:string,arg2:string):Promise<void>;

export function OpenDataRootDirectory():Promise<connection.QueryResult>;

export function OpenDownloadedUpdateDirectory():Promise<connection.QueryResult>;

export function OpenLogDirectory():Promise<connection.QueryResult>;

export function OpenServiceLogDirectory(arg1:string):Promise<connection.QueryResult>;

export function ProbeWindowsService(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ReadAppLogTail(arg1:number,arg2:string):Promise<connection.QueryResult>;

export function ReadServiceLogTail(arg1:string,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function RefreshWebViewBounds():Promise<connection.QueryResult>;

export function ResetWebViewZoom():Promise<connection.QueryResult>;

export function RestartApplication():Promise<connection.QueryResult>;

export function RestartSecurityUpdate(arg1:app.RestartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function RetrySecurityUpdateCurrentRound(arg1:app.RetrySecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function RevealSavedConnectionPrimaryPassword(arg1:string):Promise<string>;

export function SampleHostResources():Promise<connection.QueryResult>;

export function SampleServiceDetailMetrics(arg1:string):Promise<connection.QueryResult>;

export function SampleServiceMetrics(arg1:Array<string>):Promise<connection.QueryResult>;

export function SaveConnection(arg1:connection.SavedConnectionInput):Promise<connection.SavedConnectionView>;

export function SaveDownloadSourceConfig(arg1:string):Promise<app.DownloadSourceConfig>;

export function SaveGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function SaveServiceConf(arg1:string,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function SelectDataRootDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDirectory(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function SelectImageFile(arg1:string):Promise<connection.QueryResult>;

export function SelectJavaExeFile():Promise<connection.QueryResult>;

export function SelectLogDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectServiceProgramFile(arg1:string):Promise<connection.QueryResult>;

export function SelectServyEngineFile():Promise<connection.QueryResult>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMacNativeWindowControls(arg1:boolean):Promise<void>;

export function SetMainWindowBackgroundColour(arg1:boolean):Promise<connection.QueryResult>;

export function SetServiceLogRetentionDays(arg1:number):Promise<connection.QueryResult>;

export function SetUpdateChannel(arg1:string):Promise<connection.QueryResult>;

export function SetWindowTranslucency(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function Shutdown():Promise<void>;

export function StartSecurityUpdate(arg1:app.StartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function StartUpdateDownload():Promise<connection.QueryResult>;

export function TestGlobalProxyConnection(arg1:connection.TestGlobalProxyInput):Promise<connection.QueryResult>;

export function TestJVMConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function UninstallServyService(arg1:string):Promise<connection.QueryResult>;

export function UpdateConnectionVisibility(arg1:connection.ConnectionVisibilityInput):Promise<connection.SavedConnectionView>;
