// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManagedService(arg1) {
  return window['go']['app']['App']['AddManagedService'](arg1);
}

export function ApplyDataRootDirectory(arg1, arg2) {
  return window['go']['app']['App']['ApplyDataRootDirectory'](arg1, arg2);
}

export function ApplyLogDirectory(arg1) {
  return window['go']['app']['App']['ApplyLogDirectory'](arg1);
}

export function ApplyServyEnginePath(arg1) {
  return window['go']['app']['App']['ApplyServyEnginePath'](arg1);
}

export function CancelApplicationQuit() {
  return window['go']['app']['App']['CancelApplicationQuit']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckForUpdatesSilently() {
  return window['go']['app']['App']['CheckForUpdatesSilently']();
}

export function CheckServicePorts(arg1) {
  return window['go']['app']['App']['CheckServicePorts'](arg1);
}

export function ConfigureGlobalProxy(arg1, arg2) {
  return window['go']['app']['App']['ConfigureGlobalProxy'](arg1, arg2);
}

export function ControlWindowsService(arg1, arg2) {
  return window['go']['app']['App']['ControlWindowsService'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteConnections(arg1) {
  return window['go']['app']['App']['DeleteConnections'](arg1);
}

export function DescribeJavaRuntime(arg1) {
  return window['go']['app']['App']['DescribeJavaRuntime'](arg1);
}

export function DetectJavaRuntimes() {
  return window['go']['app']['App']['DetectJavaRuntimes']();
}

export function DismissSecurityUpdateReminder() {
  return window['go']['app']['App']['DismissSecurityUpdateReminder']();
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function DuplicateConnection(arg1) {
  return window['go']['app']['App']['DuplicateConnection'](arg1);
}

export function ForceQuitApplication() {
  return window['go']['app']['App']['ForceQuitApplication']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetBrandIconDataURL(arg1) {
  return window['go']['app']['App']['GetBrandIconDataURL'](arg1);
}

export function GetDataRootDirectoryInfo() {
  return window['go']['app']['App']['GetDataRootDirectoryInfo']();
}

export function GetDownloadSourceConfig() {
  return window['go']['app']['App']['GetDownloadSourceConfig']();
}

export function GetEditableSavedConnection(arg1) {
  return window['go']['app']['App']['GetEditableSavedConnection'](arg1);
}

export function GetGlobalProxyConfig() {
  return window['go']['app']['App']['GetGlobalProxyConfig']();
}

export function GetMainWindowDisplayLayout() {
  return window['go']['app']['App']['GetMainWindowDisplayLayout']();
}

export function GetSavedConnections() {
  return window['go']['app']['App']['GetSavedConnections']();
}

export function GetSecurityUpdateStatus() {
  return window['go']['app']['App']['GetSecurityUpdateStatus']();
}

export function GetServiceDirUsage(arg1, arg2) {
  return window['go']['app']['App']['GetServiceDirUsage'](arg1, arg2);
}

export function GetServiceLogRetentionDays() {
  return window['go']['app']['App']['GetServiceLogRetentionDays']();
}

export function GetServyEngineConfig() {
  return window['go']['app']['App']['GetServyEngineConfig']();
}

export function GetUpdateChannel() {
  return window['go']['app']['App']['GetUpdateChannel']();
}

export function GetUpdateDownloadTask() {
  return window['go']['app']['App']['GetUpdateDownloadTask']();
}

export function GetWindowsServiceDetail(arg1) {
  return window['go']['app']['App']['GetWindowsServiceDetail'](arg1);
}

export function ImportLegacyConnections(arg1) {
  return window['go']['app']['App']['ImportLegacyConnections'](arg1);
}

export function ImportLegacyGlobalProxy(arg1) {
  return window['go']['app']['App']['ImportLegacyGlobalProxy'](arg1);
}

export function InstallUpdateAndRestart(arg1) {
  return window['go']['app']['App']['InstallUpdateAndRestart'](arg1);
}

export function JVMApplyChange(arg1, arg2) {
  return window['go']['app']['App']['JVMApplyChange'](arg1, arg2);
}

export function JVMCancelDiagnosticCommand(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['JVMCancelDiagnosticCommand'](arg1, arg2, arg3, arg4);
}

export function JVMExecuteDiagnosticCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['JVMExecuteDiagnosticCommand'](arg1, arg2, arg3);
}

export function JVMGetMonitoringHistory(arg1, arg2) {
  return window['go']['app']['App']['JVMGetMonitoringHistory'](arg1, arg2);
}

export function JVMGetValue(arg1, arg2) {
  return window['go']['app']['App']['JVMGetValue'](arg1, arg2);
}

export function JVMListAuditRecords(arg1, arg2) {
  return window['go']['app']['App']['JVMListAuditRecords'](arg1, arg2);
}

export function JVMListDiagnosticAuditRecords(arg1, arg2) {
  return window['go']['app']['App']['JVMListDiagnosticAuditRecords'](arg1, arg2);
}

export function JVMListResources(arg1, arg2) {
  return window['go']['app']['App']['JVMListResources'](arg1, arg2);
}

export function JVMPreviewChange(arg1, arg2) {
  return window['go']['app']['App']['JVMPreviewChange'](arg1, arg2);
}

export function JVMProbeCapabilities(arg1) {
  return window['go']['app']['App']['JVMProbeCapabilities'](arg1);
}

export function JVMProbeDiagnosticCapabilities(arg1) {
  return window['go']['app']['App']['JVMProbeDiagnosticCapabilities'](arg1);
}

export function JVMStartDiagnosticSession(arg1, arg2) {
  return window['go']['app']['App']['JVMStartDiagnosticSession'](arg1, arg2);
}

export function JVMStartMonitoring(arg1) {
  return window['go']['app']['App']['JVMStartMonitoring'](arg1);
}

export function JVMStopMonitoring(arg1, arg2) {
  return window['go']['app']['App']['JVMStopMonitoring'](arg1, arg2);
}

export function ListInstalledFontFamilies() {
  return window['go']['app']['App']['ListInstalledFontFamilies']();
}

export function ListServiceEngineEvents(arg1) {
  return window['go']['app']['App']['ListServiceEngineEvents'](arg1);
}

export function ListServiceLogFiles(arg1) {
  return window['go']['app']['App']['ListServiceLogFiles'](arg1);
}

export function ListWindowsServices() {
  return window['go']['app']['App']['ListWindowsServices']();
}

export function LocateServyEngine() {
  return window['go']['app']['App']['LocateServyEngine']();
}

export function LogWindowDiagnostic(arg1, arg2) {
  return window['go']['app']['App']['LogWindowDiagnostic'](arg1, arg2);
}

export function OpenDataRootDirectory() {
  return window['go']['app']['App']['OpenDataRootDirectory']();
}

export function OpenDownloadedUpdateDirectory() {
  return window['go']['app']['App']['OpenDownloadedUpdateDirectory']();
}

export function OpenLogDirectory() {
  return window['go']['app']['App']['OpenLogDirectory']();
}

export function OpenServiceLogDirectory(arg1) {
  return window['go']['app']['App']['OpenServiceLogDirectory'](arg1);
}

export function ProbeWindowsService(arg1, arg2) {
  return window['go']['app']['App']['ProbeWindowsService'](arg1, arg2);
}

export function ReadAppLogTail(arg1, arg2) {
  return window['go']['app']['App']['ReadAppLogTail'](arg1, arg2);
}

export function ReadServiceLogTail(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadServiceLogTail'](arg1, arg2, arg3);
}

export function RefreshWebViewBounds() {
  return window['go']['app']['App']['RefreshWebViewBounds']();
}

export function ResetWebViewZoom() {
  return window['go']['app']['App']['ResetWebViewZoom']();
}

export function RestartApplication() {
  return window['go']['app']['App']['RestartApplication']();
}

export function RestartSecurityUpdate(arg1) {
  return window['go']['app']['App']['RestartSecurityUpdate'](arg1);
}

export function RetrySecurityUpdateCurrentRound(arg1) {
  return window['go']['app']['App']['RetrySecurityUpdateCurrentRound'](arg1);
}

export function RevealSavedConnectionPrimaryPassword(arg1) {
  return window['go']['app']['App']['RevealSavedConnectionPrimaryPassword'](arg1);
}

export function SampleHostResources() {
  return window['go']['app']['App']['SampleHostResources']();
}

export function SampleServiceDetailMetrics(arg1) {
  return window['go']['app']['App']['SampleServiceDetailMetrics'](arg1);
}

export function SampleServiceMetrics(arg1) {
  return window['go']['app']['App']['SampleServiceMetrics'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveDownloadSourceConfig(arg1) {
  return window['go']['app']['App']['SaveDownloadSourceConfig'](arg1);
}

export function SaveGlobalProxy(arg1) {
  return window['go']['app']['App']['SaveGlobalProxy'](arg1);
}

export function SaveServiceConf(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveServiceConf'](arg1, arg2, arg3);
}

export function SelectDataRootDirectory(arg1) {
  return window['go']['app']['App']['SelectDataRootDirectory'](arg1);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['app']['App']['SelectDirectory'](arg1, arg2);
}

export function SelectImageFile(arg1) {
  return window['go']['app']['App']['SelectImageFile'](arg1);
}

export function SelectJavaExeFile() {
  return window['go']['app']['App']['SelectJavaExeFile']();
}

export function SelectLogDirectory(arg1) {
  return window['go']['app']['App']['SelectLogDirectory'](arg1);
}

export function SelectServiceProgramFile(arg1) {
  return window['go']['app']['App']['SelectServiceProgramFile'](arg1);
}

export function SelectServyEngineFile() {
  return window['go']['app']['App']['SelectServyEngineFile']();
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetMacNativeWindowControls(arg1) {
  return window['go']['app']['App']['SetMacNativeWindowControls'](arg1);
}

export function SetMainWindowBackgroundColour(arg1) {
  return window['go']['app']['App']['SetMainWindowBackgroundColour'](arg1);
}

export function SetServiceLogRetentionDays(arg1) {
  return window['go']['app']['App']['SetServiceLogRetentionDays'](arg1);
}

export function SetUpdateChannel(arg1) {
  return window['go']['app']['App']['SetUpdateChannel'](arg1);
}

export function SetWindowTranslucency(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetWindowTranslucency'](arg1, arg2, arg3);
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function StartSecurityUpdate(arg1) {
  return window['go']['app']['App']['StartSecurityUpdate'](arg1);
}

export function StartUpdateDownload() {
  return window['go']['app']['App']['StartUpdateDownload']();
}

export function TestGlobalProxyConnection(arg1) {
  return window['go']['app']['App']['TestGlobalProxyConnection'](arg1);
}

export function TestJVMConnection(arg1) {
  return window['go']['app']['App']['TestJVMConnection'](arg1);
}

export function UninstallServyService(arg1) {
  return window['go']['app']['App']['UninstallServyService'](arg1);
}

export function UpdateConnectionVisibility(arg1) {
  return window['go']['app']['App']['UpdateConnectionVisibility'](arg1);
}
